# Generated by Django 3.2.16 on 2023-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('MeasurementId', models.AutoField(primary_key=True, serialize=False)),
                ('MeasurementDate', models.DateTimeField(auto_now_add=True)),
                ('MeasurementCo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('MeasurerId', models.CharField(max_length=50)),
                ('MeasurerName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurers',
            fields=[
                ('MeasurerId', models.AutoField(primary_key=True, serialize=False)),
                ('MeasurerName', models.CharField(max_length=50)),
            ],
        ),
    ]
